apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  ports:
  - port: 8080
  selector:
    app: node

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: rohitabraham02/node-kube:latest
        env:
          - name: ip_address # Notice that the case is different here
                                     # from the key name in the ConfigMap.
            valueFrom:
              configMapKeyRef:
               name: node-config  # The ConfigMap this value comes from.
               key: ip_address # The key to fetch.
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: mypassword